### ISSUE TITLE
Wget and Cloud commands from website failing with "Unable to Connect"

### ISSUE THREAD

**Issue by CodingBenny** [SquidDev-CC/cloud-catcher#22]
When i tried "wget https://cloud-catcher.squiddev.cc/cloud.lua" it did not work on the current version of CC:T.
I tried to http.get("https://cloud-catcher.squiddev.cc/cloud.lua") and got "nil, Unable to Connect".

It worked for me without using https.
Please update the readme

**Comment by CodingBenny** [comment]
Nevermind i got stuck after that anyway.

**Comment by SquidDev** [comment]
Older versions of Java, including the one the vanilla launcher uses, do not bundle the LetsEncrypt certificates, which means they cannot securely connect to the server.

Updating to Java 8u101 or above should fix this. However, if you're unable to, the following should work:

```
wget http://cloud-catcher.squiddev.cc/cloud.lua
cloud.lua -H XPRLAngbIkmqzDlCPBkeRwDE8et2d714
```

The `-H` flag indicates that it should connect to the remote over http rather than https.
